<?php

use Illuminate\Database\Seeder;
use App\Category;

class CategoriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = [
            ['nama_kategori' => 'Apple'],
            ['nama_kategori' => 'Samsung'],
            ['nama_kategori' => 'Xiaomi'],
            ['nama_kategori' => 'Vivo'],
            ['nama_kategori' => 'Motorola'],
            ['nama_kategori' => 'Google Pixel'],
            ['nama_kategori' => 'HTC'],
            ['nama_kategori' => 'Huawei'],
            ['nama_kategori' => 'Oppo'],
            ['nama_kategori' => 'LG'],
            ['nama_kategori' => 'Vertu'],
            ['nama_kategori' => 'Lenovo'],
            ['nama_kategori' => 'Oppo'],
            ['nama_kategori' => 'Vivo'],
            ['nama_kategori' => 'Polytron'],
            ['nama_kategori' => 'ASUS'],
            ['nama_kategori' => 'Lenovo'],
            ['nama_kategori' => 'Nokia'],
            ['nama_kategori' => 'K-touch'],
            ['nama_kategori' => 'BlackBerry'],
            ['nama_kategori' => 'Zyrex'],
            ['nama_kategori' => 'Smartfren'],
            ['nama_kategori' => 'Sony'],
            ['nama_kategori' => 'Nexian'],
            ['nama_kategori' => 'Panasonic'],
            ['nama_kategori' => 'Evercross'],
            ['nama_kategori' => 'Mito'],
            ['nama_kategori' => 'Advan'],
            ['nama_kategori' => 'Cherry Mobile'],
            ['nama_kategori' => 'HiMax'],
            ['nama_kategori' => 'Vitell'],
            ['nama_kategori' => 'Maxtron'],
            ['nama_kategori' => 'BenQ Mobile'],
            ['nama_kategori' => 'Infinix'],
            ['nama_kategori' => 'Karbonn Mobiles'],
            ['nama_kategori' => 'Micromax Mobile'],
            ['nama_kategori' => 'Onida Electronics'],
            ['nama_kategori' => 'Axioo'],
            ['nama_kategori' => 'KT Tech'],
            ['nama_kategori' => 'Oneplus'],
            ['nama_kategori' => 'Bolt'],
            ['nama_kategori' => 'Vanera'],
            ['nama_kategori' => 'Esia'],
            ['nama_kategori' => 'IMO'],
            ['nama_kategori' => 'Maxtron'],
            ['nama_kategori' => 'Zte'],
            ['nama_kategori' => 'Microsoft Mobile'],
            ['nama_kategori' => 'Sanyo'],
            ['nama_kategori' => 'Sharp'],
            ['nama_kategori' => 'Acer'],
            ['nama_kategori' => 'DELL'],
            ['nama_kategori' => 'Meizu'],
            ['nama_kategori' => 'Zyrex'],
            ['nama_kategori' => 'Himax'],
            ['nama_kategori' => 'N Gage'],
            ['nama_kategori' => 'Brondi'],
            ['nama_kategori' => 'Onda Mobile'],
            ['nama_kategori' => 'Telit'],
            ['nama_kategori' => 'VinSmart'],
            ['nama_kategori' => 'Kyocera Communications'],
            ['nama_kategori' => 'NEC'],
            ['nama_kategori' => 'Hisense'],
            ['nama_kategori' => 'Madiado'],
            ['nama_kategori' => 'Pantech'],
            ['nama_kategori' => 'Gionee'],
            ['nama_kategori' => 'Walton'],
            ['nama_kategori' => 'Konka'],
            ['nama_kategori' => 'Lanix'],
            ['nama_kategori' => 'Zonda'],
            ['nama_kategori' => 'Gresso'],
            ['nama_kategori' => 'Sitronics'],
            ['nama_kategori' => 'Yota'],
            ['nama_kategori' => 'GeeksPhone'],
            ['nama_kategori' => 'Vitelcom'],
            ['nama_kategori' => 'teXet'],
            ['nama_kategori' => 'Nextbit'],
            ['nama_kategori' => 'Goldvish'],
            ['nama_kategori' => 'Megafon'],
            ['nama_kategori' => 'E-TEN'],
            ['nama_kategori' => 'Toshiba'],
            ['nama_kategori' => 'Evertek'],
            ['nama_kategori' => 'Murefly'],
            ['nama_kategori' => 'Fixalo'],
            ['nama_kategori' => 'Berryphone'],
            ['nama_kategori' => 'Fixphone'],
            ['nama_kategori' => 'Hitachi'],
            ['nama_kategori' => 'IeuBeu'],
            ['nama_kategori' => 'Kazam'],
            ['nama_kategori' => 'Vicktyo'],
            ['nama_kategori' => 'Wellcom'],
            ['nama_kategori' => 'I-Mobile'],
            ['nama_kategori' => 'HP'],
            ['nama_kategori' => 'WePhone'],
            ['nama_kategori' => 'Siemens Mobile'],
            ['nama_kategori' => 'Grundig Mobile'],
            ['nama_kategori' => 'Luxphone'],
            ['nama_kategori' => 'Fairphone'],
            ['nama_kategori' => 'Just5'],
            ['nama_kategori' => 'Glory Phone'],
            ['nama_kategori' => 'Telefunken'],
        ];

        foreach ($categories as $category) {
            Category::create($category);
        }
    }
}
